What Is the Distance Formula?


In a two-dimensional space with two points P (x₁, y₁) and Q(x₂, y₂), the distance (d) between these two points is given by the formula:

```
d = √ (x₂ - x₁)² + (y₂ - y₁)²
```


Euclidean Distance in n Dimension

```
d = √[∑(xi – yi)²]

```

Pythagoras Theorem Statement:

Pythagoras theorem states that **“In a right-angled triangle,  the square of the hypotenuse side is equal to the sum of squares of the other two sides“**.

```

Perpendicular² + Base² = Hypotenuse²
a² + b² = c²

Where
“a” is the perpendicular,

“b” is the base,

“c” is the hypotenuse.
```

# Normal Math

In [25]:
import math

def euclidean_distance(x, y):
  distance = 0

  n = len(x) # Note: Len of xi and yi must be same

  # ∑(xi – yi)^2
  for i in range(n):
    distance += (x[i] - y[i]) ** 2

  # √distance
  euclidean_dst = math.sqrt(distance)

  return euclidean_dst


In [26]:
x = [1, 2, 3]
y = [4, 5, 6]

distance =  euclidean_distance(x, y)
print(distance)

5.196152422706632


# Using Math Dist

In [27]:
x = [1, 2, 3]
y = [4, 5, 6]

distance =  math.dist(x, y)
print(distance)
print(type(distance))

5.196152422706632
<class 'float'>


# Using NumPy

In [28]:
import numpy as np


x = [1, 2, 3]
y = [4, 5, 6]

print(type(x))

# Convert to numpy ndarray

np_x = np.array(x)
np_y = np.array(y)

print(np_x)
print(type(np_x))

<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [29]:
distance =  np.linalg.norm(np_x - np_y)
print(distance)
print(type(distance))

5.196152422706632
<class 'numpy.float64'>


# Using SciPy

In [30]:
from scipy.spatial import distance

x = [1, 2, 3]
y = [4, 5, 6]

distance =  distance.euclidean(x, y)
print(distance)
print(type(distance))

5.196152422706632
<class 'numpy.float64'>


# Pytorch

Manual Calculation

In [31]:
import torch

x = [1, 2, 3]
y = [4, 5, 6]

# Convert to tensor
tensor_x = torch.tensor(x)
tensor_y = torch.tensor(y)

distance =  torch.sqrt(torch.sum((tensor_x - tensor_y) ** 2))
print(distance)

tensor(5.1962)


Using PairwiseDistance

In [32]:
x = [1, 2, 3]
y = [4, 5, 6]

# Convert to tensor
tensor_x = torch.tensor(x)
tensor_y = torch.tensor(y)


distance =  torch.nn.PairwiseDistance()(tensor_x, tensor_y)
print(distance)

tensor(5.1962)


OR

In [33]:
!pip install -qU torchmetrics

In [34]:
import torch
from torchmetrics.functional.pairwise import pairwise_euclidean_distance

x = [1, 2, 3]
y = [4, 5, 6]

# Convert into 2D array

x = [x]
y = [y]

# Convert to tensor
tensor_x = torch.tensor(x, dtype=torch.float32)
tensor_y = torch.tensor(y, dtype=torch.float32)

distance = pairwise_euclidean_distance(tensor_x, tensor_y)
print(distance)


tensor([[5.1962]])


# Using cDist

In [35]:
x = [1, 2, 3]
y = [4, 5, 6]

# Convert into 2D array

x = [x]
y = [y]

# Convert to tensor
tensor_x = torch.tensor(x, dtype=torch.float32)
tensor_y = torch.tensor(y, dtype=torch.float32)

distance = torch.cdist(tensor_x, tensor_y, p = 2) # p = 2 for Euclidean distance
print(distance)

tensor([[5.1962]])
